# This file was generated by GoReleaser. DO NOT EDIT.
cask "kronk" do
  version "1.28.5"

  on_macos do
    on_intel do
      sha256 "1c36cc687290828efa0deb664dfab25ddcd8b6741482acefc9d9a5c4c74dea00"
      url "https://github.com/ardanlabs/kronk/releases/download/v#{version}/kronk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "3a4ec264fdd91a0db49908e8c823db101de8b97770b162a773506d0197e8e54d"
      url "https://github.com/ardanlabs/kronk/releases/download/v#{version}/kronk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "15fc35fd913ca47110b206ee147ab9f01ac829657e9e22a30387d4176f6cf656"
      url "https://github.com/ardanlabs/kronk/releases/download/v#{version}/kronk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "86fa45ac518165aa9930415e6854976e49047ddec56f33b57f09bbe953488a79"
      url "https://github.com/ardanlabs/kronk/releases/download/v#{version}/kronk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kronk"
  desc "Local LLM inference SDK and server CLI"
  homepage "https://github.com/ardanlabs/kronk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kronk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kronk"]
    end
  end

  # No zap stanza required

end
