# This file was generated by GoReleaser. DO NOT EDIT.
cask "kronk" do
  version "1.32.0"

  on_macos do
    on_arm do
      sha256 "2e5a025a8ea88810afb9f5b34a6ec9e38d50521e4003a40809ea20404c6c994c"
      url "https://github.com/ardanlabs/kronk/releases/download/v#{version}/kronk_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "24be5a1b8a41e710f6e72f512c121f8c6ce8e86bfef2a958d5f3685df7845508"
      url "https://github.com/ardanlabs/kronk/releases/download/v#{version}/kronk_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8c6303fe123ba188a848e175fb008fda70793eb6a320097573dbfcea56acbad0"
      url "https://github.com/ardanlabs/kronk/releases/download/v#{version}/kronk_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a474c4f09c2e985f9b6eebb6bec26d041e04be86b14e064ad4c50c69cbf8c436"
      url "https://github.com/ardanlabs/kronk/releases/download/v#{version}/kronk_#{version}_linux_amd64.tar.gz"
    end
  end

  name "kronk"
  desc "Local LLM inference SDK and server CLI"
  homepage "https://github.com/ardanlabs/kronk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kronk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kronk"]
    end
  end

  # No zap stanza required
end
