# This file was generated by GoReleaser. DO NOT EDIT.
cask "kronk" do
  version "1.26.0"

  on_macos do
    on_intel do
      sha256 "d72435d456c336fbbee0e0909e7345577992d5ddffb7574dd51af4af83cde2a7"
      url "https://github.com/ardanlabs/kronk/releases/download/v#{version}/kronk_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "eee579afb6e11f89283ad99d28115304eb58865cc58ccaa21171a75653b309bc"
      url "https://github.com/ardanlabs/kronk/releases/download/v#{version}/kronk_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "833309ab9eba4331f6c7af57944683d448d73431fc06d67ff76b958e04dcbd22"
      url "https://github.com/ardanlabs/kronk/releases/download/v#{version}/kronk_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "76b4f2c752a9cdcfaf7874be7f19c3fc20ae762661759ad6645001f323a194d0"
      url "https://github.com/ardanlabs/kronk/releases/download/v#{version}/kronk_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kronk"
  desc "Local LLM inference SDK and server CLI"
  homepage "https://github.com/ardanlabs/kronk"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kronk"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kronk"]
    end
  end

  # No zap stanza required

end
