# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kronk < Formula
  desc "Local LLM inference SDK and server CLI"
  homepage "https://github.com/ardanlabs/kronk"
  version "1.24.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ardanlabs/kronk/releases/download/v1.24.6/kronk_1.24.6_darwin_amd64.tar.gz"
      sha256 "795eaa7ea25498159759370b9216e4884ac00e8c7bbc0e6155529da650dd58ed"

      define_method(:install) do
        bin.install "kronk"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ardanlabs/kronk/releases/download/v1.24.6/kronk_1.24.6_darwin_arm64.tar.gz"
      sha256 "79d39e2fd6a9504cbd78fde685fa7a3d2fd4358ac8c0282e0041457fa44202e9"

      define_method(:install) do
        bin.install "kronk"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ardanlabs/kronk/releases/download/v1.24.6/kronk_1.24.6_linux_amd64.tar.gz"
      sha256 "8f058b4dc2bc431846aee9d3507798334b06ac0715597f4d131b0094cefb3467"
      define_method(:install) do
        bin.install "kronk"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ardanlabs/kronk/releases/download/v1.24.6/kronk_1.24.6_linux_arm64.tar.gz"
      sha256 "917e86a90c425b09f9aa7a8c9a928eafaf33d0c98c683bbacaadaed7f5589976"
      define_method(:install) do
        bin.install "kronk"
      end
    end
  end

  test do
    system "#{bin}/kronk", "--version"
  end
end
